version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      args:
        APPNAME: ${APPNAME_DEV}
        SHARED_WORKSPACE_HOST: ${SHARED_WORKSPACE_HOST_DEV}
        SHARED_WORKSPACE_CONTAINER: ${SHARED_WORKSPACE_CONTAINER_DEV}
        # DOCKER_TOOLS_HOST: ${DOCKER_TOOLS_HOST_DEV}
        NODE_VERSION: ${NODE_VERSION}
    image: ${APPNAME_DEV}
    container_name: ${APPNAME_DEV}
    ports:
      # フロントエンドlocalhost用
      - 8001:8001
      # Storybook用
      - 8106:8106
    volumes:
      - ./${SHARED_WORKSPACE_HOST_DEV}:${SHARED_WORKSPACE_CONTAINER_DEV}
    tty: true
