name: Check format

on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: ['prettier', 'eslint']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install Dependencies
        run: |
          cd dev/ddl-diagram-visualizer
          npm install

      - name: Run check
        run: |
          cd dev/ddl-diagram-visualizer
          if [ "${{ matrix.check }}" == "prettier" ]; then
            npm run prettier:check
          elif [ "${{ matrix.check }}" == "eslint" ]; then
            npm run eslint:check
          fi