name: Check format

on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: ['prettier', 'eslint']
    defaults:
      run:
        working-directory: /home/runner/work/ddl-diagram-visualizer/ddl-diagram-visualizer/dev/ddl-diagram-visualizer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: 
            echo $PWD

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install

      - name: Run check
        run: |
          if [ "${{ matrix.check }}" == "prettier" ]; then
            npm run prettier:check
          elif [ "${{ matrix.check }}" == "eslint" ]; then
            npm run eslint:check
          fi