name: Check format

on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: ['prettier', 'eslint']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move to the project directory
        run: cd ddl-diagram-visualizer

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run check
        run: |
          if [ "${{ matrix.check }}" == "prettier" ]; then
            npx prettier --check .
          elif [ "${{ matrix.check }}" == "eslint" ]; then
            npx eslint --ext ".js,.ts" --ignore-path .gitignore .
          fi
