name: Github Pages Deployon
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
                  cache: 'npm'

            - name: Install Dependencies
              run: |
                  cd ddl-diagram-visualizer
                  npm install

            - name: Build
              run: |
                  cd ddl-diagram-visualizer
                  npm run build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./ddl-diagram-visualizer/dist
